#!/usr/bin/env bash
# Script to display subdomain DNS information

display_info() {
    local domain="$1"
    local subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", sub, $4, $5}' sub="$subdomain"
}

if [ -z "$2" ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        display_info "$1" "$subdomain"
    done
else
    display_info "$1" "$2"
fi
